[package]
authors = ["James Grant <jamescolin.grant@gmail.com>"]
edition = "2018"
name = "tic-tac-toe-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
